(add-to-list 'load-path (expand-file-name "deft" user-emacs-directory))
(require 'deft)
(setq deft-extensions '("org"))
(setq deft-recursive t)
(global-set-key (kbd "C-c C-d") 'deft)
(provide 'init-deft)
